### ISSUE TITLE
Unused dependencies are imported into other code generators

### ISSUE THREAD

**Issue by joshcarp** [anz-bank/protoc-gen-sysl#51]
protoc-gen-go imports unused dependencies in protoc-gen-go:

```
import "sysl/options.proto";
option (sysl.namespace) = "Foo :: Bar :: Whatever";
```
generates this:

```go
import (
	_ "github.com/anz-bank/protoc-gen-sysl/sysl"
```

This option has nothing to do with go and should never be imported into the generated go code

One solution is to use the `weak` imports:
```diff
-import "sysl/options.proto";
+import weak "sysl/options.proto";
option (sysl.namespace) = "Foo :: Bar :: Whatever";
```
but this isn't fully supported, and every proto linter on earth complains that the proto spec shouldn't be using weak imports

**Comment by orlade-anz** [comment]
Linters can ignore specific rules as a workaround if `import weak` is supported "enough".

Really the import of `github.com/anz-bank/protoc-gen-sysl/sysl` should have no interesting transitive imports of its own. We can publish just that `options.pb.go` as a separate module (not part of the larger protoc-gen-sysl) and they may solve the problem.
